name: 2018 Regional DH Symposium
#baseurl: /praxis
# markdown: redcarpet
highlighter: rouge
exclude: ['_sass', 'bower_components', 'node_modules', 'Rakefile', 'README.md', 'config.rb', '_config.yml', 'Gemfile', 'Gemfile.lock', '_settings.yml', 'plugins']

domain: symposium.scholarslab.org
title: 2018 Regional DH Symposium
author: Scholars' Lab
email: bmw9t@virginia.edu
basefeed: http://www.scholarslab.org
permalink: pretty
gapi_key: 'ABQIAAAAioVG4cScdJ2Csnny8hxlzRQ0k7LmwNWN1KPzdPryee6GpBC_0hRQjOPG8jfV_sgUu5ehe3wi4vZkdA'
google_analytics:
  account: UA-12081576-3
gems:
  - jekyll-sitemap
collections:
  resources:
    output: true
    permalink: /:collection/:name/
